### ISSUE TITLE
Remove default admin user

### ISSUE THREAD

**Issue by StudioLE** [Dragontek/octobercms#4]
Is there a simple way to disable the default backend user for the instance? At present, the user admin with password admin is included.
Personally, I'd like to create a container that doesn't have a database at all but this doesn't seem possible with your container image so instead, I'd at least like to set an obscure username and password for the backend

**Comment by jmondragon** [comment]
Thank you, this is a great suggestion.  I've started to implement this capability, and was hoping you could help me with the use-case.  I know that October can be used as a flat file CMS as described [here](https://octobercms.com/support/article/ob-13), but would you expect then to pull the theme from a git repo?  or would you use the docker ONBUILD tag?  How do you envision using this image?  I'd like to make sure I capture it all.

I'm thinking that rather than generating a random user, I'll just not initialize the database at all.  I've added the ability to pass `none` to the `OCTOBER_DB_DRIVER` environment variable.

Thank you,
Josh

**Comment by StudioLE** [comment]
My use case is probably quite unique. I moved my portfolio to OctoberCMS a few years back but never actually use any of its features it simply serves my portfolio site which I update the source of. I only keep it on OctoberCMS because I don't have the time to migrate it to a static site generator.

I keep the theme, assets plugins and single repository which is copied into the container, then my hack was to replace the sqlite database with my own version. Here's the Dockerfile:

```
FROM dragontek/octobercms:latest

# Copy app directory
COPY app /usr/src/october/

# Revise the admin username
COPY config/database.sqlite /usr/src/october/storage/

# Environment variables
ENV OCTOBER_CMS_ACTIVE_THEME my_theme
ENV OCTOBER_CMS_BACKEND_URI random_string
```

**Comment by jmondragon** [comment]
Ok, I think I've captured that capability.  With your own Dockerfile, it'd look like this:

```
FROM dragontek/octobercms:latest

# Copy app directory
COPY app /usr/src/october/

# Environment variables
ENV OCTOBER_DB_DRIVER none
ENV OCTOBER_CMS_ACTIVE_THEME my_theme
ENV OCTOBER_CMS_BACKEND_URI random_string
```

Additionally, the release last week enabled the ability to pull your theme directly from git if you're interested.  See `GIT_HOSTS` and `GIT_THEMES` environment variables in the README.

The builds are done on docker hub too, so feel free to give it a try.

**Comment by StudioLE** [comment]
I've pulled the latest image and it works perfectly. Thanks for working so quickly.
